swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: |
    **HTML Injection Example: Fake Login**
    This API simulates a login page for testing purposes.

paths:
  /login:
    post:
      summary: Fake Login Endpoint
      description: Simulates a login request.
      consumes:
        - application/json
      parameters:
        - in: body
          name: credentials
          description: User login credentials
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        '200':
          description: Login successful
        '400':
          description: Bad request - Invalid input
        '401':
          description: Unauthorized - Invalid credentials
